-- Seed sites data
INSERT INTO public.sites (name, destination, country, lat, lng, difficulty, depth_min, depth_max, best_season, tags) VALUES
  ('Blue Corner', 'Palau, Micronesia', 'Palau', 7.2704, 134.3736, 'intermediate', 15, 40, 'Nov - Apr', ARRAY['wall','sharks','manta rays','strong current']),
  ('SS Thistlegorm', 'Red Sea, Egypt', 'Egypt', 27.8136, 33.9231, 'intermediate', 16, 32, 'Mar - Nov', ARRAY['wreck','WWII','history']),
  ('Manta Point', 'Nusa Penida, Indonesia', 'Indonesia', -8.7427, 115.4483, 'beginner', 5, 15, 'Apr - Oct', ARRAY['reef','manta rays','cleaning station']),
  ('Great Blue Hole', 'Belize', 'Belize', 17.3163, -87.5349, 'advanced', 30, 40, 'Apr - Jun', ARRAY['cave','stalactites','sharks']),
  ('Lembeh Strait', 'Sulawesi, Indonesia', 'Indonesia', 1.4748, 125.2355, 'intermediate', 5, 25, 'Jul - Nov', ARRAY['macro','muck diving','critters']),
  ('Silfra Fissure', 'Thingvellir, Iceland', 'Iceland', 64.2559, -21.1162, 'intermediate', 10, 18, 'May - Sep', ARRAY['cave','freshwater','visibility']),
  ('Richelieu Rock', 'Surin Islands, Thailand', 'Thailand', 9.3656, 98.0178, 'intermediate', 5, 35, 'Feb - May', ARRAY['reef','whale sharks','macro']),
  ('Barracuda Point', 'Sipadan, Malaysia', 'Malaysia', 4.1131, 118.6292, 'intermediate', 15, 40, 'Apr - Oct', ARRAY['wall','barracuda','turtles','sharks']),
  ('Darwin''s Arch', 'Galápagos, Ecuador', 'Ecuador', 1.6748, -92.0023, 'expert', 15, 30, 'Jun - Nov', ARRAY['wall','hammerhead sharks','whale sharks']),
  ('Coral Garden', 'Raja Ampat, Indonesia', 'Indonesia', -0.2382, 130.5176, 'beginner', 5, 20, 'Oct - Apr', ARRAY['reef','biodiversity','manta rays']),
  ('Navy Pier', 'Exmouth, Australia', 'Australia', -21.8109, 114.1613, 'beginner', 5, 12, 'Mar - Oct', ARRAY['reef','macro','shore dive']),
  ('Cenote Dos Ojos', 'Tulum, Mexico', 'Mexico', 20.3284, -87.3905, 'intermediate', 5, 10, 'Nov - May', ARRAY['cave','cenote','freshwater','light beams']),
  ('Tiger Beach', 'Bahamas', 'Bahamas', 26.86, -79.04, 'advanced', 6, 12, 'Oct - Mar', ARRAY['reef','tiger sharks','lemon sharks']),
  ('Poor Knights Islands', 'Northland, New Zealand', 'New Zealand', -35.4764, 174.7413, 'intermediate', 10, 40, 'Dec - May', ARRAY['wall','caves','arches']),
  ('Cocos Island', 'Costa Rica', 'Costa Rica', 5.5269, -87.0587, 'expert', 20, 40, 'Jun - Dec', ARRAY['wall','hammerhead sharks','pelagics']),
  ('Tubbataha Reef', 'Sulu Sea, Philippines', 'Philippines', 8.8574, 119.8289, 'intermediate', 10, 40, 'Mar - Jun', ARRAY['reef','sharks','UNESCO']),
  ('Shark Alley', 'Gansbaai, South Africa', 'South Africa', -34.6303, 19.3537, 'beginner', 0, 10, 'Apr - Sep', ARRAY['cage diving','great white sharks']),
  ('The Yongala', 'Townsville, Australia', 'Australia', -19.305, 147.6225, 'advanced', 15, 30, 'Apr - Nov', ARRAY['wreck','sea snakes','giant trevally']),
  ('Sardine Run', 'Wild Coast, South Africa', 'South Africa', -31.45, 29.9, 'advanced', 5, 20, 'Jun - Jul', ARRAY['pelagics','dolphins','sharks','seasonal']),
  ('Ras Mohammed', 'Sharm El Sheikh, Egypt', 'Egypt', 27.7267, 34.2589, 'beginner', 5, 30, 'Mar - Nov', ARRAY['reef','wall','colorful corals']),
  ('Malpelo Island', 'Colombia', 'Colombia', 4, -81.6, 'expert', 15, 40, 'Jan - May', ARRAY['wall','hammerhead sharks','silky sharks']),
  ('Orda Cave', 'Perm Krai, Russia', 'Russia', 56.8833, 56.8833, 'expert', 5, 22, 'Year-round', ARRAY['cave','freshwater','gypsum']),
  ('Koh Bon', 'Similan Islands, Thailand', 'Thailand', 9.067, 97.8167, 'intermediate', 10, 40, 'Nov - Apr', ARRAY['reef','manta rays','leopard sharks']),
  ('Apo Reef', 'Mindoro, Philippines', 'Philippines', 12.6667, 120.45, 'intermediate', 10, 35, 'Nov - May', ARRAY['reef','sharks','manta rays']),
  ('Daedalus Reef', 'Red Sea, Egypt', 'Egypt', 24.9167, 35.8333, 'advanced', 15, 40, 'Mar - Nov', ARRAY['wall','hammerhead sharks','oceanic whitetips']);
